global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "ec2-node"
    ec2_sd_configs:
      - region: eu-west-3         # adapter Ã  ton AWS
        access_key: ""            # facultatif si IAM Role
        secret_key: ""            # facultatif si IAM Role
        port: 9100                # Node Exporter
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_instance_id]
        target_label: ec2_id
      - source_labels: [__meta_ec2_tag_Environment]
        target_label: environment